### ISSUE TITLE
Bad OS version replacement for Windows

### ISSUE THREAD

**Issue by digitalnature** [ua-parser/uap-core#369]
Previous versions had the major version part of the family.

New versions have the version removed from the family, which I guess is OK, but the regexes weren't modified to add capturing groups for the `os_v1_replacement` ! 

For example the regex for Windows 7 needs to be changed from `(Windows NT 6\\.1)` to `(Windows NT (6\\.1))`

**Comment by commenthol** [comment]
Hi @digitalnature,
maybe this issue is already fixed by #371.

**Comment by digitalnature** [comment]
No. Windows 7, 8 etc are still missing capturing groups for v1

**Comment by commenthol** [comment]
Please post user-agents for verification.

**Comment by digitalnature** [comment]
Windows 7:

    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

regex is on line 950:

    - regex: '(Windows NT 6\.1)'
         os_replacement: 'Windows'
         os_v1_replacement: '7'

should be `(Windows (NT 6\.1))`

Same problems until line 1014
